<?php if( $this->getConfig('enabled')){ // start enable module ?>
<?php if(count($this->getItemCollection()->getItems())): ?>
    <?php
		$title = $this->getConfig('title');
        $auto = $this->getConfig('auto');
		$speed = $this->getConfig('speed');
		$show_price = $this->getConfig('show_price');
        $review = $this->getConfig('review');
		$itemsDefault = $this->getConfig('itemsDefault');
		$itemsDesktop = $this->getConfig('itemsDesktop');
		$itemsDesktopSmall = $this->getConfig('itemsDesktopSmall');
		$itemsTablet = $this->getConfig('itemsTablet');
		$itemsMobile = $this->getConfig('itemsMobile');
        $width_thumbnail = $this->getConfig('width_thumbnail');
        $height_thumbnail = $this->getConfig('height_thumbnail');
        $nav_ctrl = $this->getConfig('nav_ctrl');
        $next_back = $this->getConfig('next_back');	
    ?>
    <div class="ma-upsellslider-container">
		<?php if($title){?>
			<div class="ma-upsellslider-title modul-title"><h2><?php echo $this->__($title) ?></h2></div>
		<?php }?>
		<div class="owl-container">
			<div class="owl">
				<?php
				$rows = $this->getConfig('row_show');
				$rowi = 0;
				?>
				<?php // $this->setColumnCount(5); // uncomment this line if you want to have another number of columns. also can be changed in layout ?>
				<?php $this->resetItemsIterator() ?>
				<?php for($_i=0;$_i<$this->getRowCount();$_i++): ?>
					<?php for($_j=0;$_j<$this->getColumnCount();$_j++): ?>
						<?php if($_link=$this->getIterableItem()): ?>
						<?php if($rowi % $rows == 0) echo "<div class='ma-upsellslider-item item'>"; ?>
							<div class="item-inner">
								<div class="images-container">
									<a href="<?php echo $_link->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_link->getName()) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_link, 'small_image')->resize($width_thumbnail, $height_thumbnail) ?>" alt="<?php echo $this->htmlEscape($_link->getName()) ?>" /></a>
									<div class="actions">
										<?php if($_link->isSaleable()): ?>
											<button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_link) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
										<?php else: ?>
											<p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
										<?php endif; ?>
									</div>
								</div> 
								<div class="des-container">
									<h3 class="product-name"><a href="<?php echo $_link->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_link->getName()) ?>"><?php echo $this->htmlEscape($_link->getName()) ?></a></h3>
									 
									<?php
										if( $show_price ):
									?> 
											<?php
											$sym = Mage::app()->getLocale()->currency(Mage::app()->getStore()->getCurrentCurrencyCode())->getSymbol(); 
											$price = $_link->getPrice();
											$specialprice = $_link->getFinalPrice();
											if($price != $specialprice){
											if($specialprice != '')
											{
											echo '<div class="price-box box-special"><p class="special-price">
											<span class="price-label">Special Price</span>
											<span class="price">'.$sym.''.number_format($specialprice,2).'</span>
											</p>';
											} 
											if($price != ''){
											echo '<p class="old-price"><span class="price-label">';
											echo $this->__('Regular Price'). ': </span>';
											echo '<span class="price">'.$sym.''.number_format($price,2).'</span></p></div>';
											}
											
											}else {
											echo '<div class="price-box box-regular">
											<span class="regular-price">
											<span class="price">'.$sym.''.number_format($price,2).'</span>                                    
											</span>    
											</div>';    
											}
											?> 
									<?php endif; ?>
									<?php if( $review ): ?>
										<?php echo $this->getReviewsSummaryHtml($_link, 'short') ?>
									<?php endif; ?>
									
								</div> 
							</div>
						<?php $rowi++;?>
							<?php if($rowi % $rows == 0) echo "</div>"; ?>   
						<?php endif; ?>
					<?php endfor; ?>
				<?php endfor; ?>
				<?php if($rowi % $rows != 0) echo "</div>"; ?>
			</div>
		</div>
    </div>
	<script type="text/javascript">
		$jq(document).ready(function(){
			$jq(".ma-upsellslider-container .owl").owlCarousel({
				autoPlay : <?php if($auto) echo 'true'; else echo 'false'; ?>,
				items : <?php if($itemsDefault) echo $itemsDefault; else echo '6'; ?>,
				itemsDesktop : [1199,<?php if($itemsDesktop) echo $itemsDesktop; else echo '5'; ?>],
				itemsDesktopSmall : [991,<?php if($itemsDesktopSmall) echo $itemsDesktopSmall; else echo '3'; ?>],
				itemsTablet: [767,<?php if($itemsTablet) echo $itemsTablet; else echo '2'; ?>],
				itemsMobile : [400,<?php if($itemsMobile) echo $itemsMobile; else echo '1'; ?>],
				slideSpeed : <?php if($speed) echo $speed; else echo '500'; ?>,
				paginationSpeed : <?php if($speed) echo $speed; else echo '500'; ?>,
				rewindSpeed : <?php if($speed) echo $speed; else echo '500'; ?>,
				navigation : <?php if($next_back) echo 'true'; else echo 'false'; ?>,
				stopOnHover : true,
				pagination : <?php if($nav_ctrl) echo 'true'; else echo 'false'; ?>,
				scrollPerPage:true,
			});
		});
	</script>
<?php endif ?>
<?php } ?>