<?php /* @var $this Magentothem_Quickview_Block_Quickview */ ?>

<?php if($this->isEnabled()): ?>
    <?php $elements = $this->getQuickViewElements(); ?>
    <?php $parent_el = $this->getParentElement(); ?>
    <?php $children_el = $this->getChildrenElement(); ?>

    <div class="quickview-container">
		<a href='javascript:void(0);' class='a-qv-close' onclick='closeQVFrame()'>Close</a>
		<div id="quickview-content">
			<!-- Load quickview content into here -->
		</div>
	</div>

    <div id="quickview-bg-block">
        <!-- Quick View deep background -->
    </div>

    <div class="quickview-load-img">
        <img alt="" src="<?php echo $this->getAjaxLoadImage() ?>" />
    </div>

    <script type="text/javascript">
        <?php $flag = 'false'; if($this->isCategoryEnabled()) $flag = 'true'; ?>
        if (typeof MA == 'undefined') MA = {};
        MA.QuickView = {
            CATEGORY_ENABLE : '<?php echo $flag ?>',
            BASE_URL        : '<?php echo $this->getUrl() ?>',
            PARENT_ELEMENT  : '<?php echo $parent_el ?>',
            CHILDREN_ELEMENT: '<?php echo $children_el ?>'
        };
        <?php foreach($elements as $el): ?>
            initQuickButton('<?php echo $el ?>');
        <?php endforeach; ?>
    </script>
<?php endif; ?>