<?php if($this->getConfig('enabled') == 1):?>
	<?php
		$auto = $this->getConfig('auto');
		$speed = $this->getConfig('speed');
		$next_back = $this->getConfig('next_back');
		$nav_ctrl = $this->getConfig('nav_ctrl');
		$rows = 1;
		$i = 0;
	?>
	<div class="testimonial-sidebar">	 
		<?php $latestTestimonial = $this->getTestimonialsLast()?>
		<?php if(count($latestTestimonial) > 0):?>
			<div class="modul-title">
				<h2><?php echo $this->__('Testimonials')?></h2>
			</div>
			<div class="block-content">
			<div class="owl-container">
				<div class="owl">			
					<?php foreach($latestTestimonial as $_item):?>
						<?php if($i % $rows == 0) echo "<div class='testimonial-list'>"; ?>								
							<div class="testimonial-sidebar-content">						
								<div class="content"> 
									<div class="testimonial-content-avatar">
										<?php
											if($_item->getAvatar() != ''){
												$avatarLink = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) .$_item->getAvatar();
												?><img src="<?php echo $avatarLink ?>" alt="test" height="85" width="85" /><?php
											}
										?>
									</div>
									<div class="des-container">
										<a href="<?php echo $this->getUrl('testimonial')?>">						    
										<?php									
											$_description = $_item->getTestimonial();									
											$short_desc = $this->getContentTestimonialSidebar($_description, 150);									
											echo $short_desc;							    ?>						   
										</a>
										<div class="post-by">
											
											<div class="box-author">
												<span class="testimonial-author"><?php echo $_item->getName(); ?></span>-							
												<span class="testimonial-date"><?php echo date('F d, Y', Mage::getModel('core/date')->gmtTimestamp($_item->getCreatedTime())); ?></span>	
											</div>
																
										</div>
									</div>
								</div>						
								 			
							</div>
							<?php $i++;?>
						<?php if($i %$rows == 0) echo "</div>"; ?>                    
					<?php endforeach; ?>
						<?php if($i %$rows != 0) echo "</div>"; ?>		
				</div>
				
				</div> 
			</div>	
		<?php endif ?>	 
	</div>
	<script type="text/javascript">
		$jq(document).ready(function(){
			$jq(".testimonial-sidebar .owl").owlCarousel({
				autoPlay : <?php if($auto) echo 'true'; else echo 'false'; ?>,
				items : 1,
				itemsDesktop : [1199,1],
				itemsDesktopSmall : [991,1],
				itemsTablet: [700,1],
				itemsMobile : [400,1],
				slideSpeed : <?php if($speed) echo $speed; else echo '500'; ?>,
				paginationSpeed : <?php if($speed) echo $speed; else echo '500'; ?>,
				rewindSpeed : <?php if($speed) echo $speed; else echo '500'; ?>,
				navigation : <?php if($next_back) echo 'true'; else echo 'false'; ?>,
				stopOnHover : true,
				pagination : <?php if($nav_ctrl) echo 'true'; else echo 'false'; ?>,
				scrollPerPage:true, 
			});
			 
			
		});
		
		
	</script>
<?php endif ?>