<?php
/**
 * Netresearch_OPS_Block_Form_OpsId
 *
 * @category  design
 * @package   OPS
 * @copyright 2012 Netresearch App Factory AG <http://www.netresearch.de>
 * @author    Thomas Birke <thomas.birke@netresearch.de>
 * @license   OSL 3.0
 */
?>
<script type="text/javascript">
    Translator.add(
        'Account number must contain numbers only.',
        '<?php echo Mage::helper('ops')->__('Account number must contain numbers only.') ?>'
    );
    Translator.add(
        'Bank code must contain numbers only.',
        '<?php echo Mage::helper('ops')->__('Bank code must contain numbers only.') ?>'
    );
    Translator.add(
        'Payment failed. Please select another payment method.',
        '<?php echo Mage::helper('ops')->__('Payment failed. Please select another payment method.') ?>'
    );
</script>
<ul id="payment_form_<?php echo $this->getMethodCode() ?>" style="display:none">
    <li>
        <label for="ops_directdebit_country_id"><?php echo $this->__('country'); ?><em class="required">*</em></label><br/>
        <select title="ops_directdebit_country_id" class="required-entry" name="ops_directDebit[country_id]" id="ops_directdebit_country_id" onchange="payment.toggleOpsDirectDebitInputs(this.value)">
            <option value=""><?php echo $this->__('--Please Select--')?></option>
            <?php foreach ($this->getDirectDebitCountryIds() as $countryId) : ?>
                <option value="<?php echo $countryId; ?>"><?php echo Mage::getModel('directory/country')->loadByCode($countryId)->getName(); ?></option>
            <?php endforeach; ?>
        </select>
    </li>
    <li>
        <label for="ops_directdebit_CN"><?php echo $this->__('Account holder'); ?></label><em class="required">*</em><br/>
        <?php $cn = trim($this->getQuote()->getBillingAddress()->getFirstname() . ' ' . $this->getQuote()->getBillingAddress()->getLastname()); ?>
        <input title="CN" class="input-text required-entry" autocomplete="off" type="text" name="ops_directDebit[CN]" id="ops_directdebit_CN" length="50" value="<?php echo $cn ?>"/>
    </li>
    <li>
        <label for="ops_directdebit_account_no"><?php echo $this->__('Account number'); ?><em class="required">*</em></label><br/>
        <input title="account_no" class="input-text required-entry validate-number validate-length maximum-length-11" autocomplete="off" type="text" name="ops_directDebit[account_no]" id="ops_directdebit_account_no" maxlength="11" />
    </li>
    <li style="display:none">
        <label for="ops_directdebit_bank_code"><?php echo $this->__('Bank code'); ?><em class="required">*</em></label><br/>
        <input class="input-text required-entry validate-number validate-length" type="text" name="ops_directDebit[bank_code]" id="ops_directdebit_bank_code" maxlength="8" />
    </li>
</ul>

